/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddArtistButton: typeof import('./src/components/AddArtistButton.vue')['default']
    AddArtistDialog: typeof import('./src/components/AddArtistDialog.vue')['default']
    AddArtworkButton: typeof import('./src/components/AddArtworkButton.vue')['default']
    AddDialog: typeof import('./src/components/AddDialog.vue')['default']
    AppNavbar: typeof import('./src/components/AppNavbar.vue')['default']
    ArtistDialog: typeof import('./src/components/ArtistDialog.vue')['default']
    ArtworkDialog: typeof import('./src/components/ArtworkDialog.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataView: typeof import('primevue/dataview')['default']
    DeleteArtistButton: typeof import('./src/components/DeleteArtistButton.vue')['default']
    DeleteArtworkButton: typeof import('./src/components/DeleteArtworkButton.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EditArtistButton: typeof import('./src/components/EditArtistButton.vue')['default']
    EditArtworkButton: typeof import('./src/components/EditArtworkButton.vue')['default']
    ExploreTitle: typeof import('./src/components/ExploreTitle.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    GridTableExplore: typeof import('./src/components/GridTableExplore.vue')['default']
    HeaderExplore: typeof import('./src/components/HeaderExplore.vue')['default']
    HeaderHomePage: typeof import('./src/components/HeaderHomePage.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
